train_file: ['data/finetune/pascalparts/pascalparts_text_bbox_train_s.json']
test_file: ['data/finetune/pascalparts/pascalparts_text_bbox_val_s.json']

refcoco_data: 'data/finetune/'
#det_file: 'data/finetune/refcoco+/dets.json'
#coco_file: 'data/finetune/refcoco+/cocos.json'

image_root: 'images/pascalparts/'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size: 6
max_tokens: 40
careful_hflip: True


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}


# python3 run.py --task="pascalparts_bbox" --dist="1" --output_dir="output/grounding_scaled_lr" --load_ckpt_from="model_checkpoints/16m_base_finetune/refcoco_bbox/domain_pretrain_model_state_epoch_latest.th"







